[env]
JWT_SECRET="secret"
APP_NAME="scrippt"
DOMAIN="localhost"
GOOGLE_CLIENT_ID="82324295624-32uqo7r4j24etafpr2t0ddqt5b0etmj8.apps.googleusercontent.com"
env_files = ["./secrets.env"]

[env.test]
ENV="test"

[env.dev]
ENV="dev"

[env.prod]
ENV="prod"

[tasks.format-check]
description = "Format code using rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.lint]
description = "Lint code using clippy"
command = "cargo"
args = ["clippy"]

[tasks.test-docker]
description = "Run MongoDB and Redis for tests"
command = "docker"
args = ["compose", "-f", "docker-compose.test.yml", "up", "-d"]

[tasks.test]
env = { "ENV" = "test" }
description = "Run tests"
command = "cargo"
args = ["test", "--test", "test_*"]
dependencies = ["test-docker"]

[tasks.test-down]
description = "Stop MongoDB and Redis for tests"
command = "docker-compose"
args = ["-f", "docker-compose.test.yml", "down"]
dependencies = ["test-docker"]