name: Rust

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: davidB/rust-cargo-make@v1
      - name: Run linter
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: lint
      - name: Run format
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: format-check
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: -p ci test
